extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            
            header.media_order:
              label: MH_BASIC.MEDIA_UPLOAD
              destination: 'user/uploads'